DROP DATABASE HSC_GERMANY;

CREATE DATABASE HSC_GERMANY;

USE HSC_GERMANY;

CREATE TABLE CATEGORY(
    CAT_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50)
);

CREATE TABLE SIZESET(
    SIZESET_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50)
);

CREATE TABLE SIZE(
    SIZE_ID INT PRIMARY KEY AUTO_INCREMENT,
    SIZE INT,
    PRICE INT,
    SIZESET_ID INT,
    FOREIGN KEY(SIZESET_ID) REFERENCES SIZESET(SIZESET_ID)
);

CREATE TABLE CHOICE_SET(
    CHOICE_ID INT PRIMARY KEY AUTO_INCREMENT,
    SELECTION_TYPE VARCHAR(10),
    TITLE VARCHAR(100)
);

CREATE TABLE CHOICEITEM(
    CHOICEITEM_ID INT PRIMARY KEY AUTO_INCREMENT,
    PRICE INT,
    CHOICE VARCHAR(100),
    CHOICE_ID INT,
    FOREIGN KEY(CHOICE_ID) REFERENCES CHOICE_SET(CHOICE_ID)
);

CREATE TABLE ITEM(
    ITEM_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100),
    PRICE INT,
    CAT_ID INT,
    SIZESET_ID INT,
    IS_SIDE_DISH_OF INT,
    FOREIGN KEY (CAT_ID) REFERENCES CATEGORY(CAT_ID),
    FOREIGN KEY (SIZESET_ID) REFERENCES SIZESET(SIZESET_ID),
    FOREIGN KEY (IS_SIDE_DISH_OF) REFERENCES ITEM(ITEM_ID)
);


CREATE TABLE ITEM_CHOICE_BRIDGE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ITEM_ID INT,
    CHOICE_ID INT,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    FOREIGN KEY (CHOICE_ID) REFERENCES CHOICE_SET(CHOICE_ID)
);

CREATE TABLE ITEM_SIDEDISH_BRIDGE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ITEM_ID INT,
    SIDEDISH_ID INT,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    FOREIGN KEY (SIDEDISH_ID) REFERENCES ITEM(ITEM_ID)
);
